[package]
name = "proven-nats-server"
version.workspace = true
edition = "2024"

[dependencies]
async-nats.workspace = true
async-trait.workspace = true
bytes.workspace = true
nix.workspace = true
pem.workspace = true
proven-attestation.workspace = true
proven-bootable.workspace = true
proven-cert-store.workspace = true
proven-governance.workspace = true
proven-isolation.workspace = true
proven-messaging.workspace = true
proven-messaging-nats.workspace = true
proven-nats-monitor.workspace = true
proven-network.workspace = true
proven-store.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls-acme.workspace = true
tracing.workspace = true
uuid.workspace = true
which.workspace = true

[dev-dependencies]
bytes.workspace = true
ed25519-dalek.workspace = true
proven-attestation-mock.workspace = true
proven-governance-mock.workspace = true
proven-store-memory.workspace = true
rand.workspace = true
tracing-subscriber.workspace = true
