[package]
name = "proven-nats-server"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = { workspace = true }
nix = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
