[package]
name = "proven-sessions"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
ciborium = { workspace = true }
derive_more = { workspace = true }
ed25519-dalek = { workspace = true }
hex = { workspace = true }
proven-attestation = { workspace = true }
proven-radix-rola = { workspace = true }
proven-store = { workspace = true }
radix-common = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
