[package]
name = "proven-local"
version.workspace = true
edition = "2024"

[dependencies]
axum.workspace = true
bytes.workspace = true
ciborium.workspace = true
console.workspace = true
ed25519-dalek.workspace = true
futures.workspace = true
hickory-resolver.workspace = true
http.workspace = true
openraft.workspace = true
proven-applications.workspace = true
proven-attestation.workspace = true
proven-attestation-mock.workspace = true
proven-bitcoin-core.workspace = true
proven-bootable.workspace = true
proven-core.workspace = true
proven-engine.workspace = true
proven-ethereum-reth.workspace = true
proven-ethereum-lighthouse.workspace = true
proven-http-insecure.workspace = true
proven-http-proxy.workspace = true
proven-identity.workspace = true
proven-sessions.workspace = true
proven-network.workspace = true
proven-passkeys.workspace = true
proven-postgres.workspace = true
proven-radix-aggregator.workspace = true
proven-radix-gateway.workspace = true
proven-radix-nft-verifier-gateway.workspace = true
proven-radix-node.workspace = true
proven-runtime.workspace = true
proven-sql-engine.workspace = true
proven-storage.workspace = true
proven-storage-rocksdb.workspace = true
proven-store.workspace = true
proven-store-engine.workspace = true
proven-store-fs.workspace = true
proven-store-memory.workspace = true
proven-topology.workspace = true
proven-transport.workspace = true
proven-transport-ws.workspace = true
proven-util.workspace = true
radix-common.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower-http.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

[lints.rust]
long_running_const_eval = "allow"
