[package]
name = "proven-local"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
derive_more = { workspace = true }
proven-attestation = { workspace = true }
proven-attestation-dev = { workspace = true }
proven-http-insecure = { workspace = true }
proven-sessions = { workspace = true }
proven-store = { workspace = true }
proven-store-fs = { workspace = true }
proven-store-memory = { workspace = true }
proven-core = { workspace = true }
radix-common = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
