[package]
name = "proven-messaging"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
paste.workspace = true
proven-bootable.workspace = true
