[package]
name = "proven-messaging"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
paste = { workspace = true }
