[package]
name = "proven-locks-nats"
version.workspace = true
edition = "2024"

[dependencies]
async-nats.workspace = true
async-trait.workspace = true
bytes.workspace = true
fastrand.workspace = true
proven-locks.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
assert_matches.workspace = true
uuid.workspace = true
