[package]
name = "proven-dnscrypt-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.2"
aws-sdk-ec2 = "1.52.0"
aws-sdk-route53resolver = "1.35.0"
dns-stamp-parser = "3.0.0"
regex = "1.10.4"
tokio = { version = "1.37.0", features = ["io-util", "process"] }
tokio-util = { version = "0.7.11", features = ["rt"] }
tracing = "0.1.40"
