[package]
name = "proven-kms"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.5.1", features = ["behavior-version-latest"] }
aws-sdk-kms = "1.32.1"
derive_more = { version = "1.0.0-beta.6", features = ["from"] }
proven-attestation = { path = "../proven-attestation" }
proven-attestation-nsm = { path = "../proven-attestation-nsm" }
rand = "0.8.5"
rasn = "0.15.3"
rasn-cms = "0.15.3"
rsa = "0.9.6"
sha2 = "0.10.8"
