[package]
name = "proven-messaging-consensus"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true

futures.workspace = true
proven-attestation.workspace = true
proven-attestation-mock.workspace = true
proven-bootable.workspace = true
proven-engine.workspace = true
proven-topology.workspace = true
proven-topology-mock.workspace = true
proven-messaging.workspace = true
parking_lot.workspace = true

tokio.workspace = true

# Serialization
serde.workspace = true
serde_json.workspace = true
bytes.workspace = true
hex.workspace = true

# Logging
tracing.workspace = true

# Error handling
thiserror.workspace = true

# Collections and utilities
tokio-util.workspace = true
uuid.workspace = true

[dev-dependencies]
ed25519-dalek.workspace = true
proven-util.workspace = true
rand.workspace = true
serial_test.workspace = true
tempfile.workspace = true
tracing-test.workspace = true
tracing-subscriber.workspace = true
