[package]
name = "proven-vsock-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
cidr = "0.2.3"
derive_more = { version = "1.0.0", features = ["from"] }
tokio = { version = "1.36.0", features = [
  "io-util",
  "macros",
  "process",
  "rt",
] }
tokio-util = "0.7.12"
tracing = "0.1.40"

[target.'cfg(target_os = "linux")'.dependencies]
tokio-tun = "0.12.0"
tokio-vsock = "0.5.0"
