[package]
name = "proven-vsock-proxy"
version.workspace = true
edition = "2024"

[dependencies]
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
nix.workspace = true
