[package]
name = "proven-attestation-nsm"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.82"
aws-nitro-enclaves-nsm-api = "0.4.0"
proven-attestation = { path = "../attestation" }
serde_bytes = "0.11.15"
tokio = "1.36.0"
