[package]
name = "proven-radix-gateway-sdk"
edition = "2021"
version = "0.1.0"

[lib]
doctest = false

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
derive_more = { version = "1.0.0", features = ["from"] }
futures = "0.3.25"
http = "1.1.0"
httpclient = "0.23.14"
lazy_static = "1.4.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"

[dev-dependencies]
tokio = { version = "1.18.2", features = ["full"] }
