[package]
name = "proven-radix-gateway-sdk"
edition = "2021"
version = "0.1.0"

[lib]
doctest = false

[dependencies]
chrono = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
httpclient = { workspace = true }
lazy_static = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
