[package]
name = "proven-radix-gateway-sdk"
edition = "2024"
version.workspace = true
build = "build.rs"

[lib]
doctest = false

[dependencies]
chrono.workspace = true
http.workspace = true
progenitor-client.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true

[build-dependencies]
prettyplease.workspace = true
progenitor.workspace = true
serde_yaml.workspace = true
syn.workspace = true
