[package]
name = "proven-local-tui"
version.workspace = true
edition = "2024"

[dependencies]
# Core TUI
ratatui = "0.29.0"
crossterm = "0.29.0"

# Local cluster backend
proven-local-cluster = { path = "../local-cluster" }

# Core dependencies
proven-local.workspace = true
proven-core.workspace = true
proven-applications.workspace = true
proven-util.workspace = true
proven-topology.workspace = true
proven-topology-mock.workspace = true
proven-attestation.workspace = true
proven-attestation-mock.workspace = true

# Async and messaging
tokio.workspace = true
tokio-util.workspace = true
futures.workspace = true
parking_lot.workspace = true

# Logging and tracing
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }

# Data handling
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
rusqlite = { version = "0.32", features = ["bundled", "chrono"] }
uuid.workspace = true

# Error handling
anyhow.workspace = true
thiserror.workspace = true

# TUI-specific utilities
pokemon-rs = "1.6.6"
signal-hook = "0.3"
dirs = "6.0.0"

# Cryptography (for RPC)
ed25519-dalek.workspace = true
rand.workspace = true
hex.workspace = true

[dev-dependencies]
serial_test = "3.2.0"
tempfile = "3.8"