[package]
name = "proven-store-asm"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
aws-config.workspace = true
aws-sdk-secretsmanager.workspace = true
bytes.workspace = true
deno_error.workspace = true
paste.workspace = true
proven-store.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
