[package]
name = "proven-store-asm"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
aws-config = { workspace = true }
aws-sdk-secretsmanager = { workspace = true }
bytes = { workspace = true }
derive_more = { workspace = true }
proven-store = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
