[package]
name = "proven-store-nats"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.35.0"
async-trait = "0.1.80"
derive_more = { version = "1.0.0-beta.6", features = ["from"] }
proven-store = { path = "../proven-store" }
