[package]
name = "proven-store-nats"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.36.0"
async-trait = "0.1.82"
derive_more = { version = "1.0.0", features = ["from"] }
proven-store = { path = "../proven-store" }
