[workspace]

members = [
    "crates/proven-applications",
    "crates/proven-attestation",
    "crates/proven-attestation-dev",
    "crates/proven-attestation-nsm",
    # "crates/proven-build",
    "crates/proven-core",
    "crates/proven-dnscrypt-proxy",
    "crates/proven-enclave",
    "crates/proven-external-fs",
    "crates/proven-host",
    "crates/proven-http",
    "crates/proven-http-insecure",
    "crates/proven-http-letsencrypt",
    "crates/proven-instance-details",
    "crates/proven-imds",
    "crates/proven-kms",
    "crates/proven-local",
    "crates/proven-nats-monitor",
    "crates/proven-nats-server",
    "crates/proven-postgres",
    "crates/proven-radix-aggregator",
    "crates/proven-radix-gateway",
    "crates/proven-radix-gateway-sdk",
    "crates/proven-radix-node",
    "crates/proven-radix-rola",
    "crates/proven-runtime",
    "crates/proven-sessions",
    "crates/proven-store",
    "crates/proven-store-asm",
    "crates/proven-store-memory",
    "crates/proven-store-nats",
    "crates/proven-store-s3-sse-c",
    "crates/proven-vsock-proxy",
    "crates/proven-vsock-rpc",
    "crates/proven-vsock-tracing",
]

resolver = "2"
