[workspace]

members = [
    "crates/applications",
    "crates/attestation",
    "crates/attestation-dev",
    "crates/attestation-nsm",
    "crates/core",
    "crates/dnscrypt-proxy",
    "crates/enclave",
    "crates/external-fs",
    "crates/host",
    "crates/http",
    "crates/http-insecure",
    "crates/http-letsencrypt",
    "crates/instance-details",
    "crates/imds",
    "crates/kms",
    "crates/local",
    "crates/locks",
    "crates/locks-memory",
    "crates/nats-monitor",
    "crates/nats-server",
    "crates/postgres",
    "crates/radix-aggregator",
    "crates/radix-gateway",
    "crates/radix-gateway-sdk",
    "crates/radix-node",
    "crates/radix-rola",
    "crates/runtime",
    "crates/sessions",
    "crates/store",
    "crates/store-asm",
    "crates/store-fs",
    "crates/store-memory",
    "crates/store-nats",
    "crates/store-s3",
    "crates/vsock-proxy",
    "crates/vsock-rpc",
    "crates/vsock-tracing",
]

resolver = "2"
