[workspace]

members = [
    "crates/proven-attestation",
    "crates/proven-attestation-dev",
    "crates/proven-attestation-nsm",
    "crates/proven-core",
    # "crates/proven-doh",
    "crates/proven-enclave",
    "crates/proven-host",
    "crates/proven-imds",
    "crates/proven-kms",
    "crates/proven-nats-server",
    # "crates/proven-runtime",
    "crates/proven-store",
    "crates/proven-store-asm",
    "crates/proven-store-s3-sse-c",
    "crates/proven-vsock-proxy",
    "crates/proven-vsock-rpc",
    "crates/proven-vsock-tracing",
]

resolver = "2"
