[workspace]

members = [
    # "crates/proven-application-registry",
    # "crates/proven-asm-keyvalue",
    "crates/proven-attestation",
    "crates/proven-attestation-dev",
    "crates/proven-attestation-nsm",
    "crates/proven-core",
    "crates/proven-enclave",
    # "crates/proven-doh-proxy",
    "crates/proven-host",
    "crates/proven-imds",
    "crates/proven-nats-server",
    # "crates/proven-s3-sse-c-keyvalue",
    "crates/proven-vsock-proxy",
    "crates/proven-vsock-rpc",
    "crates/proven-vsock-tracing",
]

resolver = "2"
