
[package]
name = "proven-stream-memory"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
preinterpret = { workspace = true }
proven-stream = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
