[package]
name = "proven-transport-ws"
version = "0.1.0"
edition = "2021"

[dependencies]
proven-topology.workspace = true
proven-transport.workspace = true
async-trait.workspace = true
bytes.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
futures-util.workspace = true
tracing.workspace = true
thiserror.workspace = true
url.workspace = true
axum.workspace = true
tower.workspace = true
hyper.workspace = true
hyper-util.workspace = true
flume.workspace = true
dashmap.workspace = true

[dev-dependencies]
tracing-subscriber = "0.3"
portpicker = "0.1"
