[package]
name = "proven-transport-ws"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
axum.workspace = true
bytes.workspace = true
dashmap.workspace = true
ed25519-dalek.workspace = true
futures.workspace = true
proven-attestation.workspace = true
proven-topology.workspace = true
proven-transport.workspace = true
proven-verification.workspace = true
tokio = { workspace = true, features = ["net", "rt", "sync"] }
tokio-tungstenite.workspace = true
proven-logger.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
proven-logger-macros.workspace = true
proven-attestation-mock.workspace = true
proven-network.workspace = true
proven-topology-mock.workspace = true
proven-util.workspace = true
rand.workspace = true
reqwest.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio-test.workspace = true
tower-http = { workspace = true, features = ["cors"] }
