[package]
name = "proven-nats-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { workspace = true }
http = { workspace = true }
httpclient = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
