[package]
name = "proven-runtime"
version.workspace = true
edition = "2024"
build = "build.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
ciborium.workspace = true
deno_core.workspace = true
deno_error.workspace = true
deno_fs.workspace = true
deno_io.workspace = true
deno_permissions.workspace = true
ed25519-dalek.workspace = true
futures.workspace = true
http.workspace = true
proven-code-package.workspace = true
proven-identity.workspace = true
proven-radix-nft-verifier.workspace = true
proven-sql.workspace = true
proven-store.workspace = true
rand.workspace = true
regex.workspace = true
rustls.workspace = true
rustyscript.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
hex.workspace = true
proven-radix-nft-verifier-mock.workspace = true
proven-sql-direct.workspace = true
proven-store-memory.workspace = true
radix-transactions.workspace = true
tempfile.workspace = true

[build-dependencies]
regex.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints.rust]
long_running_const_eval = "allow"
