[package]
name = "proven-runtime"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
ciborium = { workspace = true }
deno_core = { workspace = true }
deno_graph = { workspace = true }
deno_permissions = { workspace = true }
ed25519-dalek = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
proven-locks = { workspace = true }
proven-radix-nft-verifier = { workspace = true }
proven-sql = { workspace = true }
proven-store = { workspace = true }
radix-common = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
rustyscript = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
hex = { workspace = true }
proven-locks-memory = { workspace = true }
proven-radix-nft-verifier-mock = { workspace = true }
proven-sql-direct = { workspace = true }
proven-store-memory = { workspace = true }
radix-transactions = { workspace = true }
tempfile = { workspace = true }

[build-dependencies]
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints.rust]
long_running_const_eval = "allow"
