[package]
name = "proven-runtime"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
bytes = { workspace = true }
deno_core = { workspace = true }
deno_permissions = { workspace = true }
derive_more = { workspace = true }
proven-locks = { workspace = true }
proven-sql = { workspace = true }
proven-store = { workspace = true }
regex = { workspace = true }
rustyscript = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
proven-locks-memory = { workspace = true }
proven-store-memory = { workspace = true }

[build-dependencies]
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints.rust]
long_running_const_eval = "allow"
