[package]
name = "proven-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_core = { workspace = true }
derive_more = { workspace = true }
proven-locks = { workspace = true }
proven-store = { workspace = true }
regex = { workspace = true }
rustyscript = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
proven-locks-memory = { workspace = true }
proven-store-memory = { workspace = true }
