[package]
name = "proven-store-nats"
version.workspace = true
edition = "2024"

[dependencies]
async-nats.workspace = true
async-trait.workspace = true
bytes.workspace = true
ciborium.workspace = true
deno_error.workspace = true
futures.workspace = true
paste.workspace = true
proven-store.workspace = true
thiserror.workspace = true
tokio.workspace = true
