[package]
name = "proven-store-nats"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
proven-store = { workspace = true }
tokio = { workspace = true }
