[package]
name = "proven-store-nats"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
ciborium = { workspace = true }
deno_error = { workspace = true }
futures = { workspace = true }
paste = { workspace = true }
proven-store = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
