[package]
name = "proven-http-insecure"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
axum = { version = "0.7.5", features = ["ws"] }
proven-http = { path = "../proven-http" }
tokio = "1.38.0"
tokio-util = { version = "0.7.11", features = ["rt"] }
tower-http = { version = "0.5.2", features = ["cors"] }
tracing = "0.1.40"
