[package]
name = "proven-http-insecure"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.82"
axum = { version = "0.7.5", features = ["ws"] }
proven-http = { path = "../proven-http" }
tokio = "1.36.0"
tokio-util = { version = "0.7.12", features = ["rt"] }
tower-http = { version = "0.6.0", features = ["cors"] }
tracing = "0.1.40"
