[package]
name = "proven-storage"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
hex.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
proven-logger.workspace = true

[dev-dependencies]
proven-logger-macros.workspace = true
futures.workspace = true
tokio = { workspace = true }
