services:
  # Ethereum sepolia node
  bulbasaur:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      - PROVEN_PORT=3201
      - PROVEN_NATS_CLIENT_PORT=4222
      - PROVEN_NATS_CLUSTER_PORT=6222
      - PROVEN_NODE_KEY=5625b9a5552793f321c6b1178fd20be8f8ab83fbab91a729fb9d5d222fc830c2
    ports:
      - "3201:3201/tcp"
      # reth ports
      - "30304:30304/tcp"      # P2P communication
      - "30304:30304/udp"      # P2P communication
      - "8546:8546/tcp"        # HTTP-RPC server
      # lighthouse ports
      - "9919:9919/tcp"        # Discovery and libp2p
      - "9919:9919/udp"        # Discovery and libp2p
      - "9920:9920/udp"        # QUIC
      - "5052:5052/tcp"        # HTTP API
    volumes:
      - bulbasaur-data:/tmp/proven
      - shared-config:/etc/proven
      - cargo-cache:/usr/local/cargo/registry
      - cargo-git-cache:/usr/local/cargo/git
      - target-cache:/app/target
    networks:
      proven-network:
        ipv4_address: 172.28.1.2
    hostname: bulbasaur.local
    stop_grace_period: 1m30s

  # Radix Stokenet node
  charmander:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      - PROVEN_PORT=3202
      - PROVEN_NATS_CLIENT_PORT=4223
      - PROVEN_NATS_CLUSTER_PORT=6223
      - PROVEN_NODE_KEY=76709830bdd5eee1601fc8dee71713a9dde29c9895d15b3208bd26ce0c9e266d
      - PROVEN_SKIP_VACUUM=true
    ports:
      - "3202:3202/tcp"
      # radix ports
      - "30001:30001/tcp"   # gossip port
    volumes:
      - charmander-data:/tmp/proven
      - shared-config:/etc/proven
      - cargo-cache:/usr/local/cargo/registry
      - cargo-git-cache:/usr/local/cargo/git
      - target-cache:/app/target
    networks:
      proven-network:
        ipv4_address: 172.28.1.3
    hostname: charmander.local
    stop_grace_period: 1m30s

  # Bitcoin testnet node
  squirtle:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      - PROVEN_PORT=3203
      - PROVEN_NATS_CLIENT_PORT=4224
      - PROVEN_NATS_CLUSTER_PORT=6224
      - PROVEN_NODE_KEY=9d3585d534880f32264b35c087cbc84d774b53fcbebc9649fec7bdf2db04ffe4
    ports:
      - "3203:3203/tcp"
    volumes:
      - squirtle-data:/tmp/proven
      - shared-config:/etc/proven
      - cargo-cache:/usr/local/cargo/registry
      - cargo-git-cache:/usr/local/cargo/git
      - target-cache:/app/target
    networks:
      proven-network:
        ipv4_address: 172.28.1.4
    hostname: squirtle.local
    stop_grace_period: 1m30s

  # Test client to run integration tests
  test-client:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.test
      args:
        BUILDKIT_INLINE_CACHE: 1
    depends_on:
      - bulbasaur
      - charmander
      - squirtle
    volumes:
      - shared-config:/etc/proven
    networks:
      proven-network:
        ipv4_address: 172.28.1.10
    hostname: test-client

networks:
  proven-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  bulbasaur-data:
  charmander-data:
  squirtle-data:
  shared-config:
  cargo-cache:
  cargo-git-cache:
  target-cache: 
