[package]
name = "proven-vsock-tracing"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0", features = ["from"] }
tokio = { version = "1.36.0", features = [
  "io-util",
  "macros",
  "process",
  "test-util",
  "rt",
] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tokio-vsock = "0.5.0"
