[package]
name = "proven-core"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.6", features = ["ws"] }
axum-extra = { version = "0.9.4", features = ["typed-header"] }
axum_typed_multipart = "0.12.1"
bytes = "1.7.2"
coset = { version = "0.3.8", features = ["std"] }
derive_more = { version = "1.0.0", features = ["from"] }
ed25519-dalek = { version = "2.1.1", features = ["rand_core", "signature"] }
futures = "0.3.30"
headers = "0.4.0"
hex = "0.4.3"
http-body-util = "0.1.2"
proven-attestation = { path = "../proven-attestation" }
proven-http = { path = "../proven-http" }
proven-radix-rola = { path = "../proven-radix-rola" }
proven-runtime = { path = "../proven-runtime" }
proven-sessions = { path = "../proven-sessions" }
proven-store = { path = "../proven-store" }
radix-common = "1.2.0"
rand = "0.8.5"
ring = "0.17.8"
serde = { version = "1.0.210", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.128"
tokio = { version = "1.36.0", features = [
  "io-util",
  "macros",
  "process",
  "rt",
  "rt-multi-thread",
] }
tokio-util = { version = "0.7.12", features = ["rt"] }
tracing = "0.1.40"
