[package]
name = "proven-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.35.0"
async-trait = "0.1.80"
axum = { version = "0.7.5", features = ["ws"] }
axum-extra = { version = "0.9.3", features = ["typed-header"] }
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
axum_typed_multipart = "0.11.1"
base64 = "0.22.1"
bytes = "1.6.0"
coset = { version = "0.3.7", features = ["std"] }
derive_more = { version = "1.0.0-beta.6", features = ["from"] }
ed25519-dalek = { version = "2.1.1", features = ["rand_core", "signature"] }
futures = "0.3.30"
headers = "0.4.0"
hex = "0.4.3"
http = "0.2.12"
http-body-util = "0.1.1"
proven-attestation = { path = "../proven-attestation" }
radix-common = "1.2.0"
rand = "0.8.5"
ring = "0.17.8"
rola = { git = "https://github.com/proven-network/rola.git" }
rustls = "0.21.9"
serde = { version = "1.0.201", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = [
  "io-util",
  "macros",
  "process",
  "rt",
  "rt-multi-thread",
] }
tokio-rustls-acme = { version = "0.3.0", features = ["axum"] }
tokio-stream = "0.1.15"
tokio-util = { version = "0.7.11", features = ["rt"] }
tower-http = { version = "0.5.2", features = ["cors"] }
tracing = "0.1.40"
