[package]
name = "proven-sql-nats"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
ciborium = { workspace = true }
libsql = { workspace = true }
proven-sql = { workspace = true }
proven-store = { workspace = true }
proven-stream = { workspace = true }
proven-stream-nats = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
async-nats = { workspace = true }
proven-store-memory = { workspace = true }
proven-stream-nats = { workspace = true }
tempfile = { workspace = true }
