[package]
name = "proven-sql-streamed"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
ciborium = { workspace = true }
futures = { workspace = true }
paste = { workspace = true }
proven-libsql = { workspace = true }
proven-sql = { workspace = true }
proven-store = { workspace = true }
proven-messaging = { workspace = true }
proven-messaging-memory = { workspace = true }
serde = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
async-nats = { workspace = true }
criterion = { workspace = true }
proven-messaging-nats = { workspace = true }
proven-store-memory = { workspace = true }

[[bench]]
name = "nats"
harness = false

[[bench]]
name = "memory"
harness = false
