[package]
name = "proven-sql-streamed"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
bytes.workspace = true
ciborium.workspace = true
deno_error.workspace = true
futures.workspace = true
paste.workspace = true
proven-bootable.workspace = true
proven-libsql.workspace = true
proven-sql.workspace = true
proven-store.workspace = true
proven-messaging.workspace = true
serde.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
proven-logger.workspace = true

[dev-dependencies]
proven-logger-macros.workspace = true
criterion.workspace = true
proven-messaging-memory.workspace = true
proven-store-memory.workspace = true

[[bench]]
name = "memory"
harness = false
path = "benches/memory.rs"
