[package]
name = "proven-sql-streamed"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
ciborium = { workspace = true }
proven-libsql = { workspace = true }
proven-sql = { workspace = true }
proven-store = { workspace = true }
proven-stream = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
proven-store-memory = { workspace = true }
proven-stream-memory = { workspace = true }
