[package]
name = "proven-transport-tcp"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
bytes.workspace = true
dashmap.workspace = true
ed25519-dalek.workspace = true
futures.workspace = true
hex.workspace = true
proven-attestation.workspace = true
proven-topology.workspace = true
proven-transport.workspace = true
proven-verification.workspace = true
tokio = { workspace = true, features = ["net", "rt", "sync"] }
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
proven-attestation-mock.workspace = true
proven-bootable.workspace = true
proven-topology-mock.workspace = true
proven-util.workspace = true
tokio-test.workspace = true
tracing-subscriber.workspace = true
