[package]
name = "proven-util"
version = "0.1.0"
edition = "2024"

[dependencies]
public-suffix.workspace = true
serde.workspace = true
url.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
