[package]
name = "proven-store-asm"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.80"
aws-config = { version = "1.5.1", features = ["behavior-version-latest"] }
aws-sdk-secretsmanager = "1.35.1"
derive_more = { version = "1.0.0-beta.6", features = ["from"] }
proven-store = { path = "../proven-store" }
serde_json = "1.0.118"
