[package]
name = "proven-logger-vsock"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# Core dependencies
proven-logger = { path = "../logger" }
proven-vsock-rpc = { path = "../vsock-rpc" }

# Async runtime
tokio = { workspace = true, features = ["sync", "time", "rt", "macros"] }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }

# Error handling
thiserror = { workspace = true }

# Async trait for server
async-trait = { workspace = true }

# Logging (for internal debugging)
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
proven-logger = { path = "../logger", features = ["test-support"] }