[package]
name = "proven-sql"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
deno_error = { workspace = true }
futures = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
