[package]
name = "proven-sql"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
bytes.workspace = true
deno_error.workspace = true
futures.workspace = true
paste.workspace = true
serde.workspace = true
