use std::collections::HashMap;
use std::sync::LazyLock;

// All pem data from: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/regions-certs.html
pub static REGION_PEMS: LazyLock<HashMap<&'static str, Vec<u8>>> = LazyLock::new(|| {
    let mut regions_pems = HashMap::new();

    regions_pems.insert(
        "af-south-1",
        include_bytes!("../region-pems/af-south-1.pem").to_vec(),
    );
    regions_pems.insert(
        "ap-east-1",
        include_bytes!("../region-pems/ap-east-1.pem").to_vec(),
    );
    regions_pems.insert(
        "ap-northeast-1",
        include_bytes!("../region-pems/ap-northeast-1.pem").to_vec(),
    );
    regions_pems.insert(
        "ap-northeast-2",
        include_bytes!("../region-pems/ap-northeast-2.pem").to_vec(),
    );
    regions_pems.insert(
        "ap-northeast-3",
        include_bytes!("../region-pems/ap-northeast-3.pem").to_vec(),
    );
    regions_pems.insert(
        "ap-south-1",
        include_bytes!("../region-pems/ap-south-1.pem").to_vec(),
    );
    regions_pems.insert(
        "ap-south-2",
        include_bytes!("../region-pems/ap-south-2.pem").to_vec(),
    );
    regions_pems.insert(
        "ap-southeast-1",
        include_bytes!("../region-pems/ap-southeast-1.pem").to_vec(),
    );
    regions_pems.insert(
        "ap-southeast-2",
        include_bytes!("../region-pems/ap-southeast-2.pem").to_vec(),
    );
    regions_pems.insert(
        "ap-southeast-3",
        include_bytes!("../region-pems/ap-southeast-3.pem").to_vec(),
    );
    regions_pems.insert(
        "ap-southeast-4",
        include_bytes!("../region-pems/ap-southeast-4.pem").to_vec(),
    );
    regions_pems.insert(
        "ap-southeast-5",
        include_bytes!("../region-pems/ap-southeast-5.pem").to_vec(),
    );
    regions_pems.insert(
        "ca-central-1",
        include_bytes!("../region-pems/ca-central-1.pem").to_vec(),
    );
    regions_pems.insert(
        "ca-west-1",
        include_bytes!("../region-pems/ca-west-1.pem").to_vec(),
    );
    regions_pems.insert(
        "cn-north-1",
        include_bytes!("../region-pems/cn-north-1.pem").to_vec(),
    );
    regions_pems.insert(
        "cn-northwest-1",
        include_bytes!("../region-pems/cn-northwest-1.pem").to_vec(),
    );
    regions_pems.insert(
        "eu-central-1",
        include_bytes!("../region-pems/eu-central-1.pem").to_vec(),
    );
    regions_pems.insert(
        "eu-central-2",
        include_bytes!("../region-pems/eu-central-2.pem").to_vec(),
    );
    regions_pems.insert(
        "eu-north-1",
        include_bytes!("../region-pems/eu-north-1.pem").to_vec(),
    );
    regions_pems.insert(
        "eu-south-1",
        include_bytes!("../region-pems/eu-south-1.pem").to_vec(),
    );
    regions_pems.insert(
        "eu-south-2",
        include_bytes!("../region-pems/eu-south-2.pem").to_vec(),
    );
    regions_pems.insert(
        "eu-west-1",
        include_bytes!("../region-pems/eu-west-1.pem").to_vec(),
    );
    regions_pems.insert(
        "eu-west-2",
        include_bytes!("../region-pems/eu-west-2.pem").to_vec(),
    );
    regions_pems.insert(
        "eu-west-3",
        include_bytes!("../region-pems/eu-west-3.pem").to_vec(),
    );
    regions_pems.insert(
        "il-central-1",
        include_bytes!("../region-pems/il-central-1.pem").to_vec(),
    );
    regions_pems.insert(
        "me-central-1",
        include_bytes!("../region-pems/me-central-1.pem").to_vec(),
    );
    regions_pems.insert(
        "me-south-1",
        include_bytes!("../region-pems/me-south-1.pem").to_vec(),
    );
    regions_pems.insert(
        "sa-east-1",
        include_bytes!("../region-pems/sa-east-1.pem").to_vec(),
    );
    regions_pems.insert(
        "us-east-1",
        include_bytes!("../region-pems/us-east-1.pem").to_vec(),
    );
    regions_pems.insert(
        "us-east-2",
        include_bytes!("../region-pems/us-east-2.pem").to_vec(),
    );
    regions_pems.insert(
        "us-gov-east-1",
        include_bytes!("../region-pems/us-gov-east-1.pem").to_vec(),
    );
    regions_pems.insert(
        "us-gov-west-1",
        include_bytes!("../region-pems/us-gov-west-1.pem").to_vec(),
    );
    regions_pems.insert(
        "us-west-1",
        include_bytes!("../region-pems/us-west-1.pem").to_vec(),
    );
    regions_pems.insert(
        "us-west-2",
        include_bytes!("../region-pems/us-west-2.pem").to_vec(),
    );

    regions_pems
});
