[package]
name = "proven-enclave"
version = "0.1.0"
edition = "2021"
rust-version = "1.79"

[dependencies]
cidr = "0.2.3"
derive_more = { version = "1.0.0-beta.6", features = ["from"] }
proven-attestation = { path = "../proven-attestation" }
proven-attestation-nsm = { path = "../proven-attestation-nsm" }
proven-core = { path = "../proven-core" }
proven-dnscrypt-proxy = { path = "../proven-dnscrypt-proxy" }
proven-http-letsencrypt = { path = "../proven-http-letsencrypt" }
proven-imds = { path = "../proven-imds" }
proven-instance-details = { path = "../proven-instance-details" }
proven-kms = { path = "../proven-kms" }
proven-nats-server = { path = "../proven-nats-server" }
proven-sessions = { path = "../proven-sessions" }
proven-store = { path = "../proven-store" }
proven-store-asm = { path = "../proven-store-asm" }
proven-store-memory = { path = "../proven-store-memory" }
proven-store-s3-sse-c = { path = "../proven-store-s3-sse-c" }
proven-vsock-proxy = { path = "../proven-vsock-proxy" }
proven-vsock-rpc = { path = "../proven-vsock-rpc" }
proven-vsock-tracing = { path = "../proven-vsock-tracing" }
radix-common = "1.2.0"
rand = "0.8.5"
rtnetlink = "0.14.1"
tokio = { version = "1.37.0", features = [
  "io-util",
  "macros",
  "process",
  "rt",
  "rt-multi-thread",
] }
tokio-util = { version = "0.7.11", features = ["rt"] }
tokio-vsock = "0.5.0"
tracing = "0.1.40"
tracing-panic = "0.1.2"
tracing-subscriber = "0.3.18"
