[package]
name = "proven-radix-nft-verifier-mock"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
deno_error.workspace = true
proven-radix-nft-verifier.workspace = true
thiserror.workspace = true
tokio.workspace = true
