[package]
name = "proven-vsock-rpc"
version.workspace = true
edition = "2024"

[dependencies]
# Async runtime
tokio = { workspace = true, features = ["full"] }
tokio-vsock.workspace = true
tokio-util = { workspace = true, features = ["codec"] }
tokio-stream.workspace = true

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
bincode.workspace = true
ciborium.workspace = true
bytes.workspace = true

# Error handling
thiserror.workspace = true
anyhow.workspace = true

# Utilities
async-trait.workspace = true
futures.workspace = true
pin-project.workspace = true
tracing.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
dashmap.workspace = true
parking_lot.workspace = true

# Optional dependencies
prost = { workspace = true, optional = true }
crc32fast.workspace = true

[dev-dependencies]
tokio-test.workspace = true
criterion.workspace = true
proptest.workspace = true

[features]
default = []
protobuf = ["prost"]
