[package]
name = "proven-vsock-rpc"
version.workspace = true
edition = "2024"

[dependencies]
ciborium.workspace = true
cidr.workspace = true
derive_more.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-vsock.workspace = true
tracing.workspace = true
