[package]
name = "proven-vsock-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
cidr = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true }
serde_cbor = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
tokio-vsock = { workspace = true }
