[package]
name = "proven-messaging-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true

futures.workspace = true
proven-bootable.workspace = true
proven-engine.workspace = true
proven-messaging.workspace = true
proven-transport.workspace = true
proven-storage.workspace = true
proven-topology.workspace = true
parking_lot.workspace = true

tokio.workspace = true

# Serialization
serde.workspace = true
serde_json.workspace = true
bytes.workspace = true
hex.workspace = true

# Logging
proven-logger.workspace = true

# Error handling
thiserror.workspace = true

# Collections and utilities
tokio-util.workspace = true
uuid.workspace = true
paste.workspace = true

[dev-dependencies]
proven-logger-macros.workspace = true
ed25519-dalek.workspace = true
proven-attestation-mock.workspace = true
proven-topology-mock.workspace = true
proven-util.workspace = true
rand.workspace = true
serial_test.workspace = true
tempfile.workspace = true
tracing-test.workspace = true
serde_cbor.workspace = true
proven-transport-memory.workspace = true
proven-storage-memory.workspace = true
proven-network.workspace = true
