[package]
name = "proven-radix-node"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0", features = ["from"] }
httpclient = "0.23.14"
nix = { version = "0.29.0", features = ["signal"] }
radix-common = "1.2.0"
regex = "1.10.6"
strip-ansi-escapes = "0.2.0"
tokio = { version = "1.40.0", features = ["io-util", "process"] }
tokio-util = { version = "0.7.12", features = ["rt"] }
tracing = "0.1.40"
