[package]
name = "proven-stream"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
paste = { workspace = true }
proven-messaging = { workspace = true }
