[package]
name = "proven-transport-memory"
version.workspace = true
edition = "2021"

[dependencies]
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
proven-topology.workspace = true
proven-transport.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }