[package]
name = "proven-vsock-tracing"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
tokio-vsock = { workspace = true }
