[package]
name = "proven-governance"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
bytes.workspace = true
proven-attestation.workspace = true
serde.workspace = true
tokio.workspace = true
