[package]
name = "proven-store-s3"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
base64 = { workspace = true }
blake3 = { workspace = true }
bytes = { workspace = true }
deno_error = { workspace = true }
md5 = { workspace = true }
paste = { workspace = true }
proven-store = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
