[package]
name = "proven-store-s3"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.82"
aws-config = { version = "1.5.6", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.51.0"
base64 = "0.22.1"
blake3 = "1.5.4"
derive_more = { version = "1.0.0", features = ["from"] }
md5 = "0.7.0"
proven-store = { path = "../store" }
tokio = "1.36.0"
