[package]
name = "proven-applications"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
proven-store = { workspace = true }
radix-common = { workspace = true }
serde = { workspace = true }
serde_cbor = { workspace = true }
