[package]
name = "proven-host"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.6.0"
cidr = "0.2.2"
clap = { version = "4.5.4", features = ["derive"] }
derive_more = { version = "1.0.0-beta.6", features = ["from"] }
http-body-util = "0.1.1"
hyper = { version = "1.3.1", features = ["server", "http1"] }
hyper-util = { version = "0.1.3", features = ["http1", "server", "tokio"] }
nix = { version = "0.29.0", features = ["user"] }
proven-vsock-proxy = { path = "../proven-vsock-proxy" }
proven-vsock-rpc = { path = "../proven-vsock-rpc" }
tokio = { version = "1.37.0", features = [
  "io-util",
  "macros",
  "process",
  "rt",
  "rt-multi-thread",
  "signal",
  "io-std",
] }
tokio-util = { version = "0.7.11", features = ["rt"] }
tokio-vsock = "0.5.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
