[package]
name = "proven-store-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
derive_more = { workspace = true }
proven-store = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
