[package]
name = "proven-verification"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
bytes.workspace = true
ciborium.workspace = true
coset.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
proven-attestation.workspace = true
proven-topology.workspace = true
rand.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio-test.workspace = true
