[package]
name = "proven-local-cluster"
version = "0.1.0"
edition = "2024"

[dependencies]
# Core dependencies
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
dashmap.workspace = true
dirs.workspace = true
futures.workspace = true
hex.workspace = true
parking_lot.workspace = true
rand.workspace = true
rusqlite = { workspace = true, features = ["bundled"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt", "json"] }
url.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }

# Cryptography
ed25519-dalek.workspace = true
sha2.workspace = true
coset.workspace = true
ciborium.workspace = true

# HTTP
reqwest = { workspace = true, features = ["blocking", "multipart"] }

# Proven dependencies
proven-applications.workspace = true
proven-attestation.workspace = true
proven-attestation-mock.workspace = true
proven-bootable.workspace = true
proven-engine.workspace = true
proven-gateway.workspace = true
proven-identity.workspace = true
proven-local.workspace = true
proven-passkeys.workspace = true
proven-runtime.workspace = true
proven-sessions.workspace = true
proven-topology.workspace = true
proven-topology-mock.workspace = true
proven-util.workspace = true
