
[package]
name = "proven-sql-direct"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
deno_error.workspace = true
futures.workspace = true
paste.workspace = true
proven-libsql.workspace = true
proven-sql.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
