[package]
name = "proven-attestation-dev"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.80"
coset = { version = "0.3.7", features = ["std"] }
proven-attestation = { path = "../proven-attestation" }
rand = "0.8.5"
serde = { version = "1.0.201", features = ["derive"] }
serde_cbor = "0.11.2"
