[package]
name = "proven-nats-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.35.1"
nix = { version = "0.29.0", features = ["signal"] }
regex = "1.10.5"
tokio = { version = "1.38.0", features = ["io-util", "process"] }
tokio-util = { version = "0.7.11", features = ["rt"] }
tracing = "0.1.40"
