[package]
name = "proven-nats-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.35.0"
regex = "1.10.4"
tokio = { version = "1.37.0", features = [
  "io-util",
  "macros",
  "process",
  "test-util",
  "rt",
] }
tokio-util = { version = "0.7.11", features = ["rt"] }
tracing = "0.1.40"
