[package]
name = "proven-nats-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.36.0"
nix = { version = "0.29.0", features = ["signal"] }
regex = "1.10.6"
tokio = { version = "1.40.0", features = ["io-util", "process"] }
tokio-util = { version = "0.7.12", features = ["rt"] }
tracing = "0.1.40"
