[package]
name = "proven-vsock-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
cidr = { version = "0.2.3", features = ["serde"] }
derive_more = { version = "1.0.0", features = ["from"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_cbor = "0.11.2"
tokio = { version = "1.36.0", features = [
  "io-util",
  "macros",
  "process",
  "test-util",
  "rt",
] }
tokio-vsock = "0.5.0"
tracing = "0.1.40"
