[package]
name = "proven-nats-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0-beta.6", features = ["from"] }
http = "1.1.0"
httpclient = "0.23.9"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
