[package]
name = "proven-sessions"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.82"
derive_more = { version = "1.0.0", features = ["from"] }
ed25519-dalek = { version = "2.1.1", features = ["rand_core", "signature"] }
hex = "0.4.3"
proven-attestation = { path = "../proven-attestation" }
proven-radix-rola = { path = "../proven-radix-rola" }
proven-store = { path = "../proven-store" }
radix-common = "1.2.0"
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_cbor = "0.11.2"
