[package]
name = "proven-babylon-node"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0-beta.6", features = ["from"] }
radix-common = "1.2.0"
regex = "1.10.5"
tokio = { version = "1.38.0", features = ["io-util", "process"] }
tokio-util = { version = "0.7.11", features = ["rt"] }
tracing = "0.1.40"
