[package]
name = "proven-radix-aggregator"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
nix.workspace = true
proven-bootable.workspace = true
proven-isolation.workspace = true
regex.workspace = true
reqwest.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
proven-logger.workspace = true

[dev-dependencies]
proven-logger-macros.workspace = true
proven-postgres.workspace = true
proven-radix-node.workspace = true
radix-common.workspace = true
