[package]
name = "proven-radix-aggregator"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
