[package]
name = "proven-radix-rola"
version.workspace = true
edition = "2024"

[dependencies]
bech32.workspace = true
hex.workspace = true
proven-radix-gateway-sdk.workspace = true
radix-common.workspace = true
reqwest.workspace = true
serde.workspace = true
thiserror.workspace = true
proven-logger.workspace = true

[dev-dependencies]
proven-logger-macros.workspace = true
tokio.workspace = true
