[package]
name = "proven-vsock-cac"
version.workspace = true
edition = "2024"

[dependencies]
# Core RPC framework
proven-vsock-rpc.workspace = true
tokio-vsock.workspace = true

# Async runtime
tokio = { workspace = true, features = ["full"] }
async-trait.workspace = true

# Serialization
serde = { workspace = true, features = ["derive"] }
bytes.workspace = true
bincode.workspace = true

# Networking
cidr.workspace = true

# Error handling
thiserror.workspace = true
anyhow.workspace = true

# Logging
tracing.workspace = true

[dev-dependencies]
tokio-test.workspace = true
