[package]
name = "proven-external-fs"
version.workspace = true
edition = "2024"

[dependencies]
rand.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
proven-logger.workspace = true
