[package]
name = "proven-external-fs"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
