[package]
name = "proven-transport"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
axum.workspace = true
bytes.workspace = true
ciborium.workspace = true
coset.workspace = true
dashmap.workspace = true
ed25519-dalek.workspace = true
futures.workspace = true
proven-attestation.workspace = true
proven-topology.workspace = true
proven-verification.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
proven-attestation-mock.workspace = true
proven-topology-mock.workspace = true
tokio.workspace = true
tokio-test.workspace = true
tracing-test.workspace = true
