[package]
name = "proven-locks-memory"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
proven-locks = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
