[package]
name = "proven-locks-memory"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
proven-locks.workspace = true
thiserror.workspace = true
tokio.workspace = true
proven-logger.workspace = true

[dev-dependencies]
proven-logger-macros.workspace = true
assert_matches.workspace = true
uuid.workspace = true
