[package]
name = "proven-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
console-subscriber = "0.4.0"
deno_core = "=0.313.0"
futures = "0.3.31"
once_cell = "1.20.2"
rustyscript = { git = "https://github.com/flightofthefox/rustyscript", branch = "max-heap-size" }
serde = "1.0.210"
serde_json = "1.0.128"
tokio = "1.36.0"
