[package]
name = "proven-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_core = "=0.313.0"
futures = "0.3.31"
once_cell = "1.20.2"
# Using git for now until new crate is published
rustyscript = { git = "https://github.com/rscarson/rustyscript" }
serde = "1.0.210"
serde_json = "1.0.128"
tokio = "1.36.0"
