[package]
name = "proven-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_core = "=0.313.0"
derive_more = { version = "1.0.0", features = ["from"] }
futures = "0.3.31"
once_cell = "1.20.2"
proven-store = { path = "../proven-store" }
# Using git for now until new crate is published
rustyscript = { git = "https://github.com/rscarson/rustyscript" }
serde = "1.0.210"
serde_json = "1.0.128"
sha2 = "0.10.8"
tokio = "1.36.0"

[dev-dependencies]
proven-store-memory = { path = "../proven-store-memory" }
