[package]
name = "proven-store"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
deno_error = { workspace = true }
paste = { workspace = true }
