[package]
name = "proven-radix-rola"
version = "0.1.0"
edition = "2021"

[dependencies]
bech32 = "0.11.0"
derive_more = { version = "1.0.0", features = ["from"] }
futures = "0.3.30"
hex = { version = "0.4.3" }
proven-radix-gateway-sdk = { path = "../proven-radix-gateway-sdk" }
radix-common = { version = "1.2.0", features = [
  "secp256k1_sign_and_validate",
  "serde",
] }
serde = { version = "1.0.200", features = ["derive"] }
tracing = "0.1.40"

[dev-dependencies]
tokio = { version = "1.18.2", features = ["full"] }
