[package]
name = "proven-radix-aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0-beta.6", features = ["from"] }
nix = { version = "0.29.0", features = ["signal"] }
regex = "1.10.5"
serde_json = "1.0.128"
tokio = { version = "1.38.0", features = ["io-util", "process"] }
tokio-util = { version = "0.7.11", features = ["rt"] }
tracing = "0.1.40"
