[package]
name = "proven-messaging-nats"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
paste = { workspace = true }
proven-messaging = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serial_test = { workspace = true }
