[package]
name = "proven-messaging-nats"
version.workspace = true
edition = "2024"

[dependencies]
async-nats.workspace = true
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
paste.workspace = true
proven-bootable.workspace = true
proven-messaging.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
serial_test.workspace = true
