[package]
name = "proven-attestation-nsm"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.80"
aws-nitro-enclaves-nsm-api = "0.4.0"
proven-attestation = { path = "../proven-attestation" }
serde_bytes = "0.11.14"
tracing = "0.1.40"
