[package]
name = "proven-postgres"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
once_cell.workspace = true
proven-bootable.workspace = true
proven-isolation.workspace = true
regex.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
tracing-subscriber = "0.3"
