[package]
name = "proven-postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { workspace = true }
nix = { workspace = true }
regex = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
