[package]
name = "proven-network"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core async runtime
tokio = { version = "1.38", features = ["full"] }
async-trait = "0.1"

# High-performance channels
flume = "0.11"
dashmap = "5.5"

# Serialization
bytes = "1.6"
serde = { version = "1.0", features = ["derive"] }
ciborium = "0.2"

# Error handling and logging
thiserror = "1.0"
tracing = "0.1"

# Utilities
uuid = { version = "1.8", features = ["v4", "serde"] }
pin-project-lite = "0.2"
futures = "0.3"

# Internal dependencies
proven-topology = { path = "../topology" }
proven-transport.workspace = true
proven-attestation = { path = "../attestation" }

# Crypto
ed25519-dalek.workspace = true
coset = "0.3"
rand = "0.8"

[dev-dependencies]
tokio-test = "0.4"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
proven-attestation-mock = { path = "../attestation-mock" }
proven-topology-mock = { path = "../topology-mock" }
proven-transport-tcp.workspace = true
proven-bootable = { path = "../bootable" }
proven-util = { path = "../util" }
ed25519-dalek.workspace = true
