[package]
name = "proven-network"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
bytes.workspace = true
ciborium.workspace = true
dashmap.workspace = true
ed25519-dalek.workspace = true
futures.workspace = true
hex.workspace = true
proven-bootable.workspace = true
proven-topology.workspace = true
proven-transport.workspace = true
proven-verification.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
proven-attestation-mock.workspace = true
proven-topology-mock.workspace = true
proven-transport-tcp.workspace = true
proven-util.workspace = true
tokio-test.workspace = true
tracing-subscriber.workspace = true
