[package]
name = "proven-network"
version.workspace = true
edition = "2024"

[dependencies]
bytes.workspace = true
ed25519-dalek.workspace = true
headers.workspace = true
hex.workspace = true
proven-attestation.workspace = true
proven-governance.workspace = true
proven-headers.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
async-trait.workspace = true
proven-attestation-mock.workspace = true
proven-governance-mock.workspace = true
