[package]
name = "proven-network"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
bytes.workspace = true
ciborium.workspace = true
dashmap.workspace = true
ed25519-dalek.workspace = true
futures.workspace = true
hex.workspace = true
proven-bootable.workspace = true
proven-governance.workspace = true
proven-topology.workspace = true
proven-transport.workspace = true
proven-verification.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
tracing.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }

[dev-dependencies]
tokio-test.workspace = true
