[package]
name = "proven-storage-s3"
version.workspace = true
edition = "2024"

[dependencies]
aes-gcm = { workspace = true }
async-stream = { workspace = true }
async-trait = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
ciborium = { workspace = true }
clap = { workspace = true }
crc32fast = { workspace = true }
crossbeam = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
lru = { workspace = true }
md5 = { workspace = true }
miniz_oxide = { workspace = true }
prometheus = { workspace = true }
proven-storage = { workspace = true }
proven-vsock-rpc = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-vsock.workspace = true
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

# [[bin]]
# name = "wal-server"
# path = "src/bin/wal-server.rs"

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
