[package]
name = "proven-radix-node"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
nix = { workspace = true }
once_cell = { workspace = true }
proven-isolation = { workspace = true }
radix-common = { workspace = true }
regex = { workspace = true }
strip-ansi-escapes = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full", "rt-multi-thread", "signal"] }
tracing-subscriber = { workspace = true }
