[package]
name = "proven-imds"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
derive_more = { version = "1.0.0-beta.6", features = ["from"] }
http = "0.2.12"
httpclient = "0.22.1"
pem = "3.0.4"
ring = "0.17.8"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.118"
x509-parser = { version = "0.16.0", features = ["ring", "verify"] }
